import {Injectable} from '@angular/core';
import {HttpClient} from "@angular/common/http";

import { TranslateService } from '@ngx-translate/core';

/**
 * GeoService manages users location and country
 */
@Injectable()
export class GeoServiceProvider {

    countries = {
        ""  : "Worldwide",
        "AD": "أندورا",
        "AE": "الإمارات العربية المتحدة",
        "AF": "أفغانستان",
        "AG": "أنتيغوا وباربودا",
        "AI": "أنغويلا",
        "AL": "ألبانيا",
        "AM": "أرمينيا",
        "AO": "أنغولا",
        "AQ": "القارة القطبية الجنوبية",
        "AR": "الأرجنتين",
        "AS": "ساموا الأمريكية",
        "AT": "النمسا",
        "AU": "أستراليا",
        "AW": "أروبا",
        "AX": "جزر أولاند",
        "AZ": "أذربيجان",
        "BA": "البوسنة والهرسك",
        "BB": "باربادوس",
        "BD": "بنغلاديش",
        "BE": "بلجيكا",
        "BF": "بوركينا فاسو",
        "BG": "بلغاريا",
        "BH": "البحرين",
        "BI": "بوروندي",
        "BJ": "بنين",
        "BL": "سان بارتيلمي",
        "BM": "برمودا",
        "BN": "بروناي",
        "BO": "بوليفيا",
        "BQ": "الجزر الكاريبية الهولندية",
        "BR": "البرازيل",
        "BS": "باهاماس",
        "BT": "بوتان",
        "BV": "جزيرة بوفيه",
        "BW": "بوتسوانا",
        "BY": "بيلاروسيا",
        "BZ": "بليز",
        "CA": "كندا",
        "CC": "جزر كوكس",
        "CD": "جمهورية الكونغو الديمقراطية",
        "CF": "جمهورية أفريقيا الوسطى",
        "CG": "جمهورية الكونغو",
        "CH": "سويسرا",
        "CI": "ساحل العاج",
        "CK": "جزر كوك",
        "CL": "تشيلي",
        "CM": "الكاميرون",
        "CN": "الصين",
        "CO": "كولومبيا",
        "CR": "كوستاريكا",
        "CU": "كوبا",
        "CV": "الرأس الأخضر",
        "CW": "كوراساو",
        "CX": "جزيرة عيد الميلاد",
        "CY": "قبرص",
        "CZ": "التشيك",
        "DE": "ألمانيا",
        "DJ": "جيبوتي",
        "DK": "الدنمارك",
        "DM": "دومينيكا",
        "DO": "جمهورية الدومينيكان",
        "DZ": "الجزائر",
        "EC": "الإكوادور",
        "EE": "إستونيا",
        "EG": "مصر",
        "ER": "إريتريا",
        "ES": "إسبانيا",
        "ET": "إثيوبيا",
        "FI": "فنلندا",
        "FJ": "فيجي",
        "FK": "جزر فوكلاند",
        "FM": "ولايات ميكرونيسيا المتحدة",
        "FO": "جزر فارو",
        "FR": "فرنسا",
        "GA": "الغابون",
        "GB": "المملكة المتحدة",
        "GD": "غرينادا",
        "GE": "جورجيا",
        "GF": "غويانا الفرنسية",
        "GG": "غيرنزي",
        "GH": "غانا",
        "GI": "جبل طارق",
        "GL": "غرينلاند",
        "GM": "غامبيا",
        "GN": "غينيا",
        "GP": "غوادلوب",
        "GQ": "غينيا الاستوائية",
        "GR": "اليونان",
        "GS": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
        "GT": "غواتيمالا",
        "GU": "غوام",
        "GW": "غينيا بيساو",
        "GY": "غيانا",
        "HK": "هونغ كونغ",
        "HM": "جزيرة هيرد وجزر ماكدونالد",
        "HN": "هندوراس",
        "HR": "كرواتيا",
        "HT": "هايتي",
        "HU": "المجر",
        "ID": "إندونيسيا",
        "IE": "جمهورية أيرلندا",
        "IM": "جزيرة مان",
        "IN": "الهند",
        "IO": "إقليم المحيط الهندي البريطاني",
        "IQ": "العراق",
        "IR": "إيران",
        "IS": "آيسلندا",
        "IT": "إيطاليا",
        "JE": "جيرزي",
        "JM": "جامايكا",
        "JO": "الأردن",
        "JP": "اليابان",
        "KE": "كينيا",
        "KG": "قيرغيزستان",
        "KH": "كمبوديا",
        "KI": "كيريباتي",
        "KM": "جزر القمر",
        "KN": "سانت كيتس ونيفيس",
        "KP": "كوريا الشمالية",
        "KR": "كوريا الجنوبية",
        "KW": "الكويت",
        "KY": "جزر كايمان",
        "KZ": "كازاخستان",
        "LA": "لاوس",
        "LB": "لبنان",
        "LC": "سانت لوسيا",
        "LI": "ليختنشتاين",
        "LK": "سريلانكا",
        "LR": "ليبيريا",
        "LS": "ليسوتو",
        "LT": "ليتوانيا",
        "LU": "لوكسمبورغ",
        "LV": "لاتفيا",
        "LY": "ليبيا",
        "MA": "المغرب",
        "MC": "موناكو",
        "MD": "مولدافيا",
        "ME": "الجبل الأسود",
        "MF": "سانت مارتن الفرنسية",
        "MG": "مدغشقر",
        "MH": "جزر مارشال",
        "MK": "جمهورية مقدونيا",
        "ML": "مالي",
        "MM": "بورما",
        "MN": "منغوليا",
        "MO": "ماكاو",
        "MP": "جزر ماريانا الشمالية",
        "MQ": "مارتينيك",
        "MR": "موريتانيا",
        "MS": "مونتسرات",
        "MT": "مالطا",
        "MU": "موريشيوس",
        "MV": "جزر المالديف",
        "MW": "مالاوي",
        "MX": "المكسيك",
        "MY": "ماليزيا",
        "MZ": "موزمبيق",
        "NA": "ناميبيا",
        "NC": "كاليدونيا الجديدة",
        "NE": "النيجر",
        "NF": "جزيرة نورفولك",
        "NG": "نيجيريا",
        "NI": "نيكاراغوا",
        "NL": "هولندا",
        "NO": "النرويج",
        "NP": "نيبال",
        "NR": "ناورو",
        "NU": "نييوي",
        "NZ": "نيوزيلندا",
        "OM": "عمان",
        "PA": "بنما",
        "PE": "بيرو",
        "PF": "بولينزيا الفرنسية",
        "PG": "بابوا غينيا الجديدة",
        "PH": "الفلبين",
        "PK": "باكستان",
        "PL": "بولندا",
        "PM": "سان بيير وميكلون",
        "PN": "جزر بيتكيرن",
        "PR": "بورتوريكو",
        "PS": "فلسطين",
        "PT": "البرتغال",
        "PW": "بالاو",
        "PY": "باراغواي",
        "QA": "قطر",
        "RE": "ريونيون",
        "RO": "رومانيا",
        "RS": "صربيا",
        "RU": "روسيا",
        "RW": "رواندا",
        "SA": "السعودية",
        "SB": "جزر سليمان",
        "SC": "سيشل",
        "SD": "السودان",
        "SE": "السويد",
        "SG": "سنغافورة",
        "SH": "سانت هيلينا وأسينشين وتريستان دا كونا",
        "SI": "سلوفينيا",
        "SJ": "سفالبارد ويان ماين",
        "SK": "سلوفاكيا",
        "SL": "سيراليون",
        "SM": "سان مارينو",
        "SN": "السنغال",
        "SO": "الصومال",
        "SR": "سورينام",
        "SS": "جنوب السودان",
        "ST": "ساو تومي وبرينسيب",
        "SV": "السلفادور",
        "SX": "سينت مارتن",
        "SY": "سوريا",
        "SZ": "سوازيلاند",
        "TC": "جزر توركس وكايكوس",
        "TD": "تشاد",
        "TF": "أراض فرنسية جنوبية وأنتارتيكية",
        "TG": "توغو",
        "TH": "تايلاند",
        "TJ": "طاجيكستان",
        "TK": "توكلو",
        "TL": "تيمور الشرقية",
        "TM": "تركمانستان",
        "TN": "تونس",
        "TO": "تونغا",
        "TR": "تركيا",
        "TT": "ترينيداد وتوباغو",
        "TV": "توفالو",
        "TW": "تايوان",
        "TZ": "تنزانيا",
        "UA": "أوكرانيا",
        "UG": "أوغندا",
        "UM": "جزر الولايات المتحدة الصغيرة النائية",
        "US": "الولايات المتحدة",
        "UY": "الأوروغواي",
        "UZ": "أوزبكستان",
        "VA": "الفاتيكان",
        "VC": "سانت فنسنت والجرينادين",
        "VE": "فنزويلا",
        "VG": "الجزر العذراء البريطانية",
        "VI": "جزر العذراء الأمريكية",
        "VN": "فيتنام",
        "VU": "فانواتو",
        "WF": "والس وفوتونا",
        "WS": "ساموا",
        "YE": "اليمن",
        "YT": "مايوت",
        "ZA": "جنوب أفريقيا",
        "ZM": "زامبيا",
        "ZW": "زيمبابوي"
    };

    phones = {
        'AF': '+93',
        'AL': '+355',
        'DZ': '+213',
        'AS': '+1684',
        'AD': '+376',
        'AO': '+244',
        'AI': '+1264',
        'AQ': '+672',
        'AG': '+1268',
        'AR': '+54',
        'AM': '+374',
        'AW': '+297',
        'AU': '+61',
        'AT': '+43',
        'AZ': '+994',
        'BS': '+1242',
        'BH': '+973',
        'BD': '+880',
        'BB': '+1246',
        'BY': '+375',
        'BE': '+32',
        'BZ': '+501',
        'BJ': '+229',
        'BM': '+1441',
        'BT': '+975',
        'BO': '+591',
        'BA': '+387',
        'BW': '+267',
        'BR': '+55',
        'BN': '+673',
        'BG': '+359',
        'BF': '+226',
        'BI': '+257',
        'KH': '+855',
        'CM': '+237',
        'CA': '+1',
        'CV': '+238',
        'KY': '+1345',
        'CF': '+236',
        'TD': '+235',
        'CL': '+56',
        'CN': '+86',
        'CX': '+53',
        'CC': '+61',
        'CO': '+57',
        'KM': '+269',
        'CD': '+243',
        'CG': '+242',
        'CK': '+682',
        'CR': '+506',
        'CI': '+225',
        'HR': '+385',
        'CU': '+53',
        'CY': '+357',
        'CZ': '+420',
        'DK': '+45',
        'DJ': '+253',
        'DM': '+1767',
        'DO': '+1809',
        'TP': '+670',
        'EC': '+593',
        'EG': '+20',
        'SV': '+503',
        'GQ': '+240',
        'ER': '+291',
        'EE': '+372',
        'ET': '+251',
        'FK': '+500',
        'FO': '+298',
        'FJ': '+679',
        'FI': '+358',
        'FR': '+33',
        'GF': '+594',
        'PF': '+689',
        'GA': '+241',
        'GM': '+220',
        'GE': '+995',
        'DE': '+49',
        'GH': '+233',
        'GI': '+350',
        'GR': '+30',
        'GL': '+299',
        'GD': '+1473',
        'GP': '+590',
        'GU': '+1671',
        'GT': '+502',
        'GN': '+224',
        'GW': '+245',
        'GY': '+592',
        'HT': '+509',
        'HN': '+504',
        'HK': '+852',
        'HU': '+36',
        'IS': '+354',
        'IN': '+91',
        'ID': '+62',
        'IR': '+98',
        'IQ': '+964',
        'IE': '+353',
        'IT': '+39',
        'JM': '+1876',
        'JP': '+81',
        'JO': '+962',
        'KZ': '+7',
        'KE': '+254',
        'KI': '+686',
        'KP': '+850',
        'KR': '+82',
        'KW': '+965',
        'KG': '+996',
        'LA': '+856',
        'LV': '+371',
        'LB': '+961',
        'LS': '+266',
        'LR': '+231',
        'LY': '+218',
        'LI': '+423',
        'LT': '+370',
        'LU': '+352',
        'MO': '+853',
        'MK': '+389',
        'MG': '+261',
        'MW': '+265',
        'MY': '+60',
        'MV': '+960',
        'ML': '+223',
        'MT': '+356',
        'MH': '+692',
        'MQ': '+596',
        'MR': '+222',
        'MU': '+230',
        'YT': '+269',
        'MX': '+52',
        'FM': '+691',
        'MD': '+373',
        'MC': '+377',
        'MN': '+976',
        'MS': '+1664',
        'MA': '+212',
        'MZ': '+258',
        'MM': '+95',
        'NA': '+264',
        'NR': '+674',
        'NP': '+977',
        'NL': '+31',
        'AN': '+599',
        'NC': '+687',
        'NZ': '+64',
        'NI': '+505',
        'NE': '+227',
        'NG': '+234',
        'NU': '+683',
        'NF': '+672',
        'MP': '+1670',
        'NO': '+47',
        'OM': '+968',
        'PK': '+92',
        'PW': '+680',
        'PS': '+970',
        'PA': '+507',
        'PG': '+675',
        'PY': '+595',
        'PE': '+51',
        'PH': '+63',
        'PL': '+48',
        'PT': '+351',
        'PR': '+1787',
        'QA': '+974',
        'RE': '+262',
        'RO': '+40',
        'RU': '+7',
        'RW': '+250',
        'SH': '+290',
        'KN': '+1869',
        'LC': '+1758',
        'PM': '+508',
        'VC': '+1784',
        'WS': '+685',
        'SM': '+378',
        'ST': '+239',
        'SA': '+966',
        'SN': '+221',
        'SC': '+248',
        'SL': '+232',
        'SG': '+65',
        'SK': '+421',
        'SI': '+386',
        'SB': '+677',
        'SO': '+252',
        'ZA': '+27',
        'ES': '+34',
        'LK': '+94',
        'SD': '+249',
        'SR': '+597',
        'SZ': '+268',
        'SE': '+46',
        'CH': '+41',
        'SY': '+963',
        'TW': '+886',
        'TJ': '+992',
        'TZ': '+255',
        'TH': '+66',
        'TK': '+690',
        'TO': '+676',
        'TT': '+1868',
        'TN': '+216',
        'TR': '+90',
        'TM': '+993',
        'TC': '+1649',
        'TV': '+688',
        'UG': '+256',
        'UA': '+380',
        'AE': '+971',
        'GB': '+44',
        'US': '+1',
        'UY': '+598',
        'UZ': '+998',
        'VU': '+678',
        'VA': '+418',
        'VE': '+58',
        'VN': '+84',
        'VI': '+1284',
        'VQ': '+1340',
        'WF': '+681',
        'YE': '+967',
        'ZM': '+260',
        'ZW': '+263'
    };

    country_english=
    {
     "BD": "Bangladesh",
     "BE": "Belgium",
     "BF": "Burkina Faso",
     "BG": "Bulgaria",
     "BA": "Bosnia and Herzegovina",
     "BB": "Barbados",
     "WF": "Wallis and Futuna",
     "BL": "Saint Barthelemy",
     "BM": "Bermuda",
     "BN": "Brunei",
     "BO": "Bolivia",
     "BH": "Bahrain",
     "BI": "Burundi",
     "BJ": "Benin",
     "BT": "Bhutan",
     "JM": "Jamaica",
     "BV": "Bouvet Island",
     "BW": "Botswana",
     "WS": "Samoa",
     "BQ": "Bonaire",
     "BR": "Brazil",
     "BS": "Bahamas",
     "JE": "Jersey",
     "BY": "Belarus",
     "BZ": "Belize",
     "RU": "Russia",
     "RW": "Rwanda",
     "RS": "Serbia",
     "TL": "East Timor",
     "RE": "Reunion",
     "TM": "Turkmenistan",
     "TJ": "Tajikistan",
     "RO": "Romania",
     "TK": "Tokelau",
     "GW": "Guinea-Bissau",
     "GU": "Guam",
     "GT": "Guatemala",
     "GS": "South Georgia and the South Sandwich Islands",
     "GR": "Greece",
     "GQ": "Equatorial Guinea",
     "GP": "Guadeloupe",
     "JP": "Japan",
     "GY": "Guyana",
     "GG": "Guernsey",
     "GF": "French Guiana",
     "GE": "Georgia",
     "GD": "Grenada",
     "GB": "United Kingdom",
     "GA": "Gabon",
     "SV": "El Salvador",
     "GN": "Guinea",
     "GM": "Gambia",
     "GL": "Greenland",
     "GI": "Gibraltar",
     "GH": "Ghana",
     "OM": "Oman",
     "TN": "Tunisia",
     "JO": "Jordan",
     "HR": "Croatia",
     "HT": "Haiti",
     "HU": "Hungary",
     "HK": "Hong Kong",
     "HN": "Honduras",
     "HM": "Heard Island and McDonald Islands",
     "VE": "Venezuela",
     "PR": "Puerto Rico",
     "PS": "Palestinian Territory",
     "PW": "Palau",
     "PT": "Portugal",
     "SJ": "Svalbard and Jan Mayen",
     "PY": "Paraguay",
     "IQ": "Iraq",
     "PA": "Panama",
     "PF": "French Polynesia",
     "PG": "Papua New Guinea",
     "PE": "Peru",
     "PK": "Pakistan",
     "PH": "Philippines",
     "PN": "Pitcairn",
     "PL": "Poland",
     "PM": "Saint Pierre and Miquelon",
     "ZM": "Zambia",
     "EH": "Western Sahara",
     "EE": "Estonia",
     "EG": "Egypt",
     "ZA": "South Africa",
     "EC": "Ecuador",
     "IT": "Italy",
     "VN": "Vietnam",
     "SB": "Solomon Islands",
     "ET": "Ethiopia",
     "SO": "Somalia",
     "ZW": "Zimbabwe",
     "SA": "Saudi Arabia",
     "ES": "Spain",
     "ER": "Eritrea",
     "ME": "Montenegro",
     "MD": "Moldova",
     "MG": "Madagascar",
     "MF": "Saint Martin",
     "MA": "Morocco",
     "MC": "Monaco",
     "UZ": "Uzbekistan",
     "MM": "Myanmar",
     "ML": "Mali",
     "MO": "Macao",
     "MN": "Mongolia",
     "MH": "Marshall Islands",
     "MK": "Macedonia",
     "MU": "Mauritius",
     "MT": "Malta",
     "MW": "Malawi",
     "MV": "Maldives",
     "MQ": "Martinique",
     "MP": "Northern Mariana Islands",
     "MS": "Montserrat",
     "MR": "Mauritania",
     "IM": "Isle of Man",
     "UG": "Uganda",
     "TZ": "Tanzania",
     "MY": "Malaysia",
     "MX": "Mexico",
     "IL": "Israel",
     "FR": "France",
     "IO": "British Indian Ocean Territory",
     "SH": "Saint Helena",
     "FI": "Finland",
     "FJ": "Fiji",
     "FK": "Falkland Islands",
     "FM": "Micronesia",
     "FO": "Faroe Islands",
     "NI": "Nicaragua",
     "NL": "Netherlands",
     "NO": "Norway",
     "NA": "Namibia",
     "VU": "Vanuatu",
     "NC": "New Caledonia",
     "NE": "Niger",
     "NF": "Norfolk Island",
     "NG": "Nigeria",
     "NZ": "New Zealand",
     "NP": "Nepal",
     "NR": "Nauru",
     "NU": "Niue",
     "CK": "Cook Islands",
     "XK": "Kosovo",
     "CI": "Ivory Coast",
     "CH": "Switzerland",
     "CO": "Colombia",
     "CN": "China",
     "CM": "Cameroon",
     "CL": "Chile",
     "CC": "Cocos Islands",
     "CA": "Canada",
     "CG": "Republic of the Congo",
     "CF": "Central African Republic",
     "CD": "Democratic Republic of the Congo",
     "CZ": "Czech Republic",
     "CY": "Cyprus",
     "CX": "Christmas Island",
     "CR": "Costa Rica",
     "CW": "Curacao",
     "CV": "Cape Verde",
     "CU": "Cuba",
     "SZ": "Swaziland",
     "SY": "Syria",
     "SX": "Sint Maarten",
     "KG": "Kyrgyzstan",
     "KE": "Kenya",
     "SS": "South Sudan",
     "SR": "Suriname",
     "KI": "Kiribati",
     "KH": "Cambodia",
     "KN": "Saint Kitts and Nevis",
     "KM": "Comoros",
     "ST": "Sao Tome and Principe",
     "SK": "Slovakia",
     "KR": "South Korea",
     "SI": "Slovenia",
     "KP": "North Korea",
     "KW": "Kuwait",
     "SN": "Senegal",
     "SM": "San Marino",
     "SL": "Sierra Leone",
     "SC": "Seychelles",
     "KZ": "Kazakhstan",
     "KY": "Cayman Islands",
     "SG": "Singapore",
     "SE": "Sweden",
     "SD": "Sudan",
     "DO": "Dominican Republic",
     "DM": "Dominica",
     "DJ": "Djibouti",
     "DK": "Denmark",
     "VG": "British Virgin Islands",
     "DE": "Germany",
     "YE": "Yemen",
     "DZ": "Algeria",
     "US": "United States",
     "UY": "Uruguay",
     "YT": "Mayotte",
     "UM": "United States Minor Outlying Islands",
     "LB": "Lebanon",
     "LC": "Saint Lucia",
     "LA": "Laos",
     "TV": "Tuvalu",
     "TW": "Taiwan",
     "TT": "Trinidad and Tobago",
     "TR": "Turkey",
     "LK": "Sri Lanka",
     "LI": "Liechtenstein",
     "LV": "Latvia",
     "TO": "Tonga",
     "LT": "Lithuania",
     "LU": "Luxembourg",
     "LR": "Liberia",
     "LS": "Lesotho",
     "TH": "Thailand",
     "TF": "French Southern Territories",
     "TG": "Togo",
     "TD": "Chad",
     "TC": "Turks and Caicos Islands",
     "LY": "Libya",
     "VA": "Vatican",
     "VC": "Saint Vincent and the Grenadines",
     "AE": "United Arab Emirates",
     "AD": "Andorra",
     "AG": "Antigua and Barbuda",
     "AF": "Afghanistan",
     "AI": "Anguilla",
     "VI": "U.S. Virgin Islands",
     "IS": "Iceland",
     "IR": "Iran",
     "AM": "Armenia",
     "AL": "Albania",
     "AO": "Angola", "AQ": "Antarctica",
     "AS": "American Samoa",
     "AR": "Argentina",
     "AU": "Australia",
     "AT": "Austria",
     "AW": "Aruba",
     "IN": "India",
     "AX": "Aland Islands",
     "AZ": "Azerbaijan",
     "IE": "Ireland",
     "ID": "Indonesia",
     "UA": "Ukraine",
     "QA": "Qatar",
     "MZ": "Mozambique"
    }

    /**
     * get name of country of given ios code
     * @param {string} code ISO-2 code in uppercase
     * @returns {any}
     */
    getCountryName(code) {
        return this.countries[('' + code).toUpperCase()];
    }
 
    /**
     * @ignore
     */
    constructor(private http: HttpClient,
                public translate: TranslateService,) {
    }

    /**
     * Request for location info
     * @returns {Observable<Object>}
     */
    getMyLocation(): Promise<any> {
        return this.http.get("https://iplist.cc/api/").toPromise()
            .then(data => {
                console.log('GeoService', data);
                if (data && data.hasOwnProperty('countrycode')) {
                    return data;
                } else {
                    return '';
                }
            }).catch(() => {
                return '';
            });
    }

    getCountryPhone(code) {
        return this.phones[code];
    }

    getCountriesData(trans: any) {
        let data = {};
        for (let key in this.countries) {
            if (this.countries.hasOwnProperty(key)) {
                if (this.countries[key] && this.phones[key]) {
                    data[key] = {
                        code: key.toLowerCase(),
                        name: trans.instant('COUNTRIES.' + key),//this.countries[key]
                        phone: this.phones[key]
                    }
                }
            }
        }
        return data;
    }

    getAllCountries(){
        let data=[];
        let i=0;
        
        Object.keys(this.countries).map((key) => {
          //   console.log('key',key);
          let a={
              code:key,
              name:this.countries[key]
          }
          data.push(a);
           i++;
          })
        return data;
    }
    getArCountries(){
       let data=[];
        let i=0;
        
        Object.keys(this.countries).map((key) => {
          //   console.log('key',key);
          if( key != ''){
              let a={
                  code:key,
                  name:this.countries[key]
              }
              data.push(a);
               i++;
          }
          })
        return data; 
    }

    getEnCountries(){
        let data=[];
        let i=0;
        
        Object.keys(this.country_english).map((key) => {
          //   console.log('key',key);
          let a={
              code:key,
              name:this.country_english[key]
          }
          data.push(a);
           i++;
          })
        return data;
    }
    getCountryDetails(code){
        let data={
            country_en_name:'',
            country_code:'',
            country_ar_name:''
        };
        Object.keys(this.country_english).map((key) => {
          if(code== key){
              data.country_en_name=this.country_english[key];
              data.country_code=key;
          }
        })
        Object.keys(this.countries).map((key) => {
          if(code== key){
              data.country_ar_name=this.countries[key];
          }
        })
        return data;
    }

}
